Fixed color not ending and confirming

diff --git a/sshtui b/sshtui
--- a/sshtui
+++ b/sshtui
@@ -1,106 +1,36 @@
-#!/usr/bin/env bash
+#!/bin/env bash
 
-HOSTS_FILE="$HOME/etc/.sshtui/servers.conf"
+RED=$(echo -e '\033[31m')
+GREEN=$(echo -e '\033[0;32m')
+PURPLE=$(echo -e '\033[0;35m')
+NC=$(echo -e '\033[0m')
 
-mkdir -p "$(dirname "$HOSTS_FILE")"
-if [ ! -f "$HOSTS_FILE" ]; then
-  touch "$HOSTS_FILE"
-fi
+echo -e "${PURPLE}sshTUI installer:"
+read -r -p "Would you like to install the sshTUI? [y/N] " response
 
-FZF_COLORS="bg:#010409,bg+:#264f78,fg:#e6edf3,fg+:#e6edf3,hl:#58a6ff,hl+:#79c0ff,info:#39c5cf,prompt:#56d364,pointer:#ff7b72,marker:#bc8cff,header:#d29922,border:#484f58"
+case "$response" in
+    [yY][eE][sS]|[yY][tT]
 
-get_servers() {
-  grep -v -e '^[[:space:]]*#' -e '^[[:space:]]*$' "$HOSTS_FILE"
-}
+        echo ""
+        echo "-----------------Downloading------------------"
+        echo ""
 
-while true; do
-  SELECTED_LINE=$( (get_servers; echo "[*] Settings") | fzf \
-    --prompt="Select Server: " \
-    --layout=reverse \
-    --border \
-    --style full \
-    --color="$FZF_COLORS" \
-    --header="sshTUI - TUI Wrapper for ssh | [ESC] Exit [TYPE] Search [ENTER] Connect")
+    curl -s -o sshtui https://raw.githubusercontent.com/grzesiowski1223/sshtui/main/install_sshtui.sh
 
-  if [ -z "$SELECTED_LINE" ]; then
-    clear
-    echo "Exited/Canceled."
-    break
-  fi
-
-  if [[ "$SELECTED_LINE" == "[*]"* ]]; then
-    while true; do
-      clear
-      SETTING_CHOICE=$(echo -e "[+] Add New Server\n[-] Remove Server\n[<] Back to Main Menu" | fzf \
-        --prompt="Settings: " \
-        --layout=reverse \
-        --border \
-        --style full \
-        --color="$FZF_COLORS" \
-        --header="Manage your server list")
-
-      if [ -z "$SETTING_CHOICE" ] || [[ "$SETTING_CHOICE" == "[<]"* ]]; then
-        clear
-        break
-      fi
-
-      if [[ "$SETTING_CHOICE" == "[+]"* ]]; then
-        clear
-        echo "=== Adding New Server ==="
-        read -p "Enter alias/name (e.g., vps-prod): " name
-        read -p "Enter SSH address (e.g., user@ip): " addr
-        
-        if [ -n "$name" ] && [ -n "$addr" ]; then
-          printf "%-13s %s\n" "$name" "$addr" >> "$HOSTS_FILE"
-          echo "Server added successfully!"
-        else
-          echo "Cancelled: Name or Address cannot be empty."
+        if [[ ! -f sshtui ]]; then
+            echo -e "${RED}Download failed. Please check the URL or your internet connection.${NC}"
+            exit 1
         fi
-        sleep 1.5
 
-      elif [[ "$SETTING_CHOICE" == "[-]"* ]]; then
-        clear
-        SERVER_TO_REMOVE=$(get_servers | fzf \
-          --prompt="Select Server to REMOVE: " \
-          --layout=reverse \
-          --border \
-          --style full \
-          --color="$FZF_COLORS" \
-          --header="WARNING: Press ENTER to delete, ESC to cancel")
+        sed -i "s|^IPADDRESS=.*$|IPADDRESS=\"$ip\"|" oss
+        chmod +x sshtui
+        sudo cp sshtui /usr/local/bin/
 
-        if [ -n "$SERVER_TO_REMOVE" ]; then
-          spin='-\|/'
-          for i in {1..10}; do
-            printf "\r[%c] Removing server from the list..." "${spin:i%4:1}"
-            sleep 0.1
-          done
-          printf "\r\033[K"
-
-          sed -i "\|$SERVER_TO_REMOVE|d" "$HOSTS_FILE"
-          echo "Server removed successfully!"
-          sleep 1.5
-        else
-          echo "Cancelled: No server was removed."
-          sleep 1
-        fi
-      fi
-    done
-    continue
-
-  else
-    SELECT_HOST=$(echo "$SELECTED_LINE" | awk '{print $2}')
-
-    clear
-    echo "Connecting with: $SELECT_HOST..."
-
-    spin='-\|/'
-    for i in {1..15}; do
-      printf "\r[%c] Initializing connection..." "${spin:i%4:1}"
-      sleep 0.1
-    done
-    
-    printf "\r\033[K" 
-    ssh "$SELECT_HOST"
-    break
-  fi
-done
+        echo -e "${GREEN}The installation is successful.${NC}"
+        echo "You can now run 'sshtui' as a command!"
+        ;;
+    *)
+        echo "Exiting..."
+        exit
+        ;;
+esac
